language: python

sudo: required
dist: trusty

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

install:
  - travis_retry pip install -r requirements-test.txt

before_script:
  - flake8 taiga

script: nosetests --with-coverage --cover-package=taiga

after_success: codecov

jobs:
  include:
    - stage: package
      install:
        - sudo apt-get install -yq --no-install-suggests --no-install-recommends
          devscripts fakeroot equivs
        - mk-build-deps -i -s sudo -t 'apt-get -yq' debian/control
        - echo 'APT::Default-Release "trusty";' | sudo tee /etc/apt/apt.conf
        - echo 'deb http://archive.ubuntu.com/ubuntu xenial main' |
          sudo tee /etc/apt/sources.list.d/xenial.list
        - sudo apt-get update
        - sudo apt-get install -yq --no-install-suggests --no-install-recommends
          -t xenial
          python-dateutil python-requests python-six
          python3-dateutil python3-requests python3-six
      script: make deb
      before_script: skip
      after_success: skip
